- hosts: Master:Slave
  tasks:
  - set_fact: port="9001"
          
  - name: "coping hadoop s/w"
    copy:
            src: "/hadoop/hadoop-1.2.1-1.x86_64.rpm"  
            dest: "/root"

  - name: "coping jdk s/w"
    copy:
            src: "/hadoop/jdk-8u171-linux-x64.rpm"
            dest: "/root"

  - name: "clearing cache"
    shell: "echo 3 > /proc/sys/vm/drop_caches"

  - name: "installing jdk"
    shell: "rpm -i jdk-8u171-linux-x64.rpm"
    ignore_errors: yes

  - name: "installing hadoop"
    shell: "rpm -i hadoop-1.2.1-1.x86_64.rpm --force"
    ignore_errors: yes

- hosts: Master
  vars:
          nn_dir: "nn"
  tasks:
  - name: "creating a namenode directory"
    file:
            name: "{{ nn_dir }}"
            state: directory

  - name: "coping hdfs config file to hdfs-site.xml"
    template:
            src: "/hadoop/nn_hdfs-site.xml"
            dest: "/etc/hadoop/hdfs-site.xml"

  - name: "coping core config file to core-site.xml"
    template:
            src: "/hadoop/nn_core-site.xml"
            dest: "/etc/hadoop/core-site.xml"

  - name: "formating the namenode"
    shell: "echo Y | hadoop namenode -format"
    register: "format"

  - name: "format sccess code"
    debug:
            var: format.stderr_lines

  - name: "Starting the namenode"
    shell: "hadoop-daemon.sh start namenode"

  - name: "jps"
    shell: "jps"
    register: "show" 

  - debug:
          var: show.stdout_lines



- hosts: Slave
  vars:
          dn_dir: "dn"
  tasks:
  - name: "creating a datanode directory"
    file:
            name: "{{  dn_dir }}"   
            state: directory

  - name: "coping hdfs config file to hdfs-site.xml" 
    template:
            src: "/hadoop/dn_hdfs-site.xml"
            dest: "/etc/hadoop/hdfs-site.xml"

  - name: "coping core config file to core-site.xml"
    template:
            src: "/hadoop/dn_core-site.xml"
            dest: "/etc/hadoop/core-site.xml"

  - name: "starting the datanode"
    shell: "hadoop-daemon.sh start datanode"

  - name: "jps" 
    shell: "jps"
    register: "show"


